name: qml37
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - pip
  - pip:
      - pennylane==0.37.0
      - pennylane-lightning[gpu]==0.37.0
      - pennylane-qiskit==0.34.0
      - qiskit==1.1.0
      - torch==2.1.1
      - torchvision==0.16.1
      - numpy==1.26.4
      - scikit-learn==1.3.2
      - pandas==2.1.4
      - matplotlib==3.8.2
      - seaborn==0.13.2
      - click==8.1.7
      - tqdm==4.66.2
